version: '3'
services:
  backend:
    depends_on: 
      - 'postgres'
    container_name: gs-ciencia-api
    build: .
    ports: 
      - 8000:8000
  postgres:
    container_name: gs-ciencia-db
    image: postgres:13.1-alpine
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
    ports: 
      - 5432:5432